
services:

  db:
    build:
      context: ./db_image
      dockerfile: Dockerfile
    container_name: medsync-db-instance
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: medsync_db

      MYSQL_ROOT_AUTHENTICATION_PLUGIN: 'mysql_native_password'

    volumes:
      - medsync_db_data:/var/lib/mysql
    restart: unless-stopped

  medsync.api:
    build:
      context: .
      dockerfile: MedSync.Api/Dockerfile
    container_name: medsync-api-instance
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
      MYSQL_SERVER_MEDSYNC: db
      MYSQL_DB_MEDSYNC: medsync_db
      MYSQL_PORT_MEDSYNC: 3306
      MYSQL_USER_MEDSYNC: root
      MYSQL_PASSWORD: 123456
    depends_on:
      - db
    restart: unless-stopped

volumes:
  medsync_db_data: